"""This is an autogenerated main.py created by the humanloop CLI tool"""
from programmatic.main import start_humanloop


# Edit these lines to use your own dataset!
import pandas as pd
#from programmatic.examples import load_snips

dataset = pd.read_csv('/app/empty_homes_data/OCOD_FULL_2022_02.csv')

labels = ["single", "multi"]
#dataset, labels, ground_truths = load_snips()


def start(host=None, port=None, log_level="warning", debug=False):
    start_humanloop(
        host=host,
        port=port,
        dataset=dataset,
        labels=labels,
        #ground_truths=ground_truths,
        log_level=log_level,
        debug=debug,
    )
