"""This is an autogenerated main.py created by the humanloop CLI tool"""
import pandas as pd

from programmatic.main import start_humanloop


##
## Necessary for using a function module
##
import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).parent))

# Edit the lines below to use your own dataset!

""" 
Dataset is a pd.DataFrame. The only mandatory column is `text`, 
which should have a `string` dtype. The rest is up to you. 
"""
dataset = pd.read_csv('/app/enhance_ocod/data/property_address_only.csv')



"""
Add spaCy Doc object under the `doc` column.
(This is done automatically if the "doc" column does not exist)
"""
from programmatic.integrations import SpacyTokenization
dataset["doc"] = SpacyTokenization()


"""
Labels is a simple list of strings
"""
labels = ['building_name', 'postcode', 'street_name', 'street_number', 'unit_id', 'unit_type', 'city', 'number_filter','last_do_not_use']


ground_truths = pd.read_csv("/app/enhance_ocod/data/gt_dev_for_programmatic.csv")


""" 
ground_truths is another pd.DataFrame. It should have these columns:

    `datapoint_id`: row index into `dataset`. 
    `label`: string matching something in the `labels` list
    `start`: text start offset
    `end`: text end offset
"""


def start(host=None, port=None, log_level="warning", debug=False):
    start_humanloop(
        host=host,
        port=port,
        dataset=dataset,
        labels=labels,
        ground_truths=ground_truths,
        log_level=log_level,
        debug=debug,
    )
    
#docker run --rm -p 8889:8889 -it -v $(pwd):/app jonno/humanloop:latest run /app/enhance_ocod/humanloop_2 --port=8889 --host=0.0.0.0

