"""This is an autogenerated main.py created by the humanloop CLI tool"""
from programmatic.main import start_humanloop
import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).parent))

# Edit these lines to use your own dataset!
#from programmatic.examples import load_snips

#dataset, labels, ground_truths = load_snips()
import pandas as pd

dataset = pd.read_csv('/app/empty_homes_data/property_address_only.csv')

print(dataset.index.dtype)

labels = ['building_name', 'postcode', 'street_name', 'street_number', 'unit_id', 'unit_type', 'city', 'number_filter','last_do_not_use']

ground_truths = pd.read_csv("/app/empty_homes_data/gt_dev_for_programmatic.csv")

def start(host=None, port=None, log_level="warning", debug=False):
    start_humanloop(
        host=host,
        port=port,
        dataset=dataset,
        labels=labels,
        ground_truths=ground_truths,
        log_level=log_level,
        debug=debug,
    )
