"""
train_on_absurd.py

Trains a ModernBERT NER model on a CSV dataset generated by generate_ner_dataset.py.

IMPORTANT: This script depends on the enhance_ocod package and is designed to be
copied into enhance_ocod/scripts/ (or run from any environment where enhance_ocod
is installed) at train time. It is NOT part of the enhance_ocod repo itself.

Usage (from enhance_ocod root with enhance_ocod installed):
    python scripts/train_on_absurd.py \\
        --train_csv enhance_ocod/data/training_data/absurd_ner_training_data.csv \\
        --model_suffix absurd_v1

The validation set is always the fixed ground-truth test set at:
    <enhance_ocod_root>/data/training_data/ner_ready/ground_truth_test_set_labels.json
"""

import argparse
from pathlib import Path

import pandas as pd
import torch
from transformers import (
    AutoModelForTokenClassification,
    DataCollatorForTokenClassification,
    Trainer,
    TrainingArguments,
)

from enhance_ocod.preprocess import dataframe_to_ner_format
from enhance_ocod.training import (
    NERDataProcessor,
    create_label_list,
    evaluate_model_performance,
)

torch.set_float32_matmul_precision("medium")

ENTITY_TYPES = [
    "building_name",
    "street_name",
    "street_number",
    "number_filter",
    "unit_id",
    "unit_type",
    "city",
    "postcode",
]


def parse_arguments():
    parser = argparse.ArgumentParser(
        description="Train ModernBERT NER model on absurd_data synthetic CSV."
    )
    parser.add_argument("--train_csv", required=True,
                        help="Path to CSV produced by generate_ner_dataset.py")
    parser.add_argument("--model_suffix", required=True,
                        help="Suffix for output dir: address_parser_<suffix>")
    parser.add_argument("--num_epochs", type=int, default=6)
    parser.add_argument("--batch_size", type=int, default=16)
    parser.add_argument("--learning_rate", type=float, default=5e-5)
    parser.add_argument("--max_length", type=int, default=128)
    return parser.parse_args()


def main():
    args = parse_arguments()

    SCRIPT_DIR = Path(__file__).parent.absolute()
    model_name = "answerdotai/ModernBERT-base"

    val_data_path = str(
        SCRIPT_DIR / ".." / "data" / "training_data"
        / "ner_ready" / "ground_truth_test_set_labels.json"
    )
    output_dir_name = f"address_parser_{args.model_suffix}"
    output_dir = str(SCRIPT_DIR / ".." / "models" / output_dir_name)
    final_model_path = SCRIPT_DIR / ".." / "models" / output_dir_name / "final_model"
    performance_folder = SCRIPT_DIR / ".." / "data" / "model_performance"

    print("Configuration:")
    print(f"  Training CSV:    {args.train_csv}")
    print(f"  Validation:      ground_truth_test_set_labels.json")
    print(f"  Output dir:      {output_dir}")
    print("-" * 50)

    label_list = create_label_list(ENTITY_TYPES)
    print(f"Label list: {label_list}")

    processor = NERDataProcessor(label_list, model_name)

    print("Loading and converting training CSV...")
    df = pd.read_csv(args.train_csv)
    train_data = dataframe_to_ner_format(df)

    print("Loading validation data...")
    val_data = processor.load_json_data(val_data_path)

    train_dataset = processor.create_dataset(train_data, args.max_length)
    val_dataset = processor.create_dataset(val_data, args.max_length)

    print(f"Training examples:   {len(train_dataset)}")
    print(f"Validation examples: {len(val_dataset)}")

    print(f"Loading model: {model_name}")
    model = AutoModelForTokenClassification.from_pretrained(
        model_name,
        num_labels=len(label_list),
        id2label=processor.id2label,
        label2id=processor.label2id,
        ignore_mismatched_sizes=True,
    )

    data_collator = DataCollatorForTokenClassification(
        tokenizer=processor.tokenizer,
        pad_to_multiple_of=8,
    )

    training_args = TrainingArguments(
        output_dir=output_dir,
        overwrite_output_dir=True,
        num_train_epochs=args.num_epochs,
        per_device_train_batch_size=args.batch_size,
        per_device_eval_batch_size=args.batch_size,
        warmup_steps=500,
        weight_decay=0.01,
        logging_dir=f"{output_dir}/logs",
        logging_steps=500,
        eval_strategy="epoch",
        save_strategy="epoch",
        save_total_limit=1,
        load_best_model_at_end=True,
        metric_for_best_model="f1",
        greater_is_better=True,
        push_to_hub=False,
        report_to="tensorboard",
        learning_rate=args.learning_rate,
    )

    trainer = Trainer(
        model=model,
        args=training_args,
        data_collator=data_collator,
        train_dataset=train_dataset,
        eval_dataset=val_dataset,
        tokenizer=processor.tokenizer,
        compute_metrics=processor.compute_entity_metrics,
    )

    print("Starting training...")
    trainer.train()

    trainer.model.save_pretrained(final_model_path)
    processor.tokenizer.save_pretrained(final_model_path)
    print(f"Final model saved to: {final_model_path}")

    evaluate_model_performance(
        model_path=final_model_path,
        data_path=val_data_path,
        output_dir=performance_folder,
        dataset_name=f"test_{args.model_suffix}",
        max_length=args.max_length,
    )

    print("Training and evaluation complete!")


if __name__ == "__main__":
    main()
